name: Snyk Test

on:
  workflow_dispatch:

jobs:
  snyk-test:
    runs-on: test-arc-runner-scale-set
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.3
      
      - name: Setup Snyk
        uses: snyk/actions/setup@master
      
      - uses: actions/setup-java@v5.7.0
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Run Snyk Monitor
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
